### ISSUE TITLE
Npm install finished project does not work.

### ISSUE THREAD

**Issue by m-schou** [johnkomarnicki/FireBlogs-YouTube#10]
Npm install finished project does not work. Do you know why?
Should i not be able to see some of the interface at least?

Thanks.

_________________

emoved 8 packages, changed 24 packages, and audited 215 packages in 4s

10 packages are looking for funding
  run `npm fund` for details

3 moderate severity vulnerabilities

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
ms@Ms-MacBook-Pro FireBlogs-YouTube-Finished-Source-Code % npm -v                       
8.3.0
ms@Ms-MacBook-Pro FireBlogs-YouTube-Finished-Source-Code % sudo npm npm install -g npm@latest
Unknown command: "npm"

To see a list of supported npm commands, run:
  npm help
ms@Ms-MacBook-Pro FireBlogs-YouTube-Finished-Source-Code % sudo npm install -g npm@latest 

changed 14 packages, and audited 215 packages in 3s

10 packages are looking for funding
  run `npm fund` for details

3 moderate severity vulnerabilities

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
ms@Ms-MacBook-Pro FireBlogs-YouTube-Finished-Source-Code % npm -v                            
8.3.0
ms@Ms-MacBook-Pro FireBlogs-YouTube-Finished-Source-Code % sudo npm install -g npm@latest
ms@Ms-MacBook-Pro FireBlogs-YouTube-Finished-Source-Code % npm install                  
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /Users/ms/Projects/FireBlogs-YouTube-Finished-Source-Code/node_modules/acorn
npm ERR! dest /Users/ms/Projects/FireBlogs-YouTube-Finished-Source-Code/node_modules/.acorn-N9aErJTn
npm ERR! errno -66
npm ERR! ENOTEMPTY: directory not empty, rename '/Users/ms/Projects/FireBlogs-YouTube-Finished-Source-Code/node_modules/acorn' -> '/Users/ms/Projects/FireBlogs-YouTube-Finished-Source-Code/node_modules/.acorn-N9aErJTn'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ms/.npm/_logs/2022-01-06T16_53_18_596Z-debug-0.log
ms@Ms-MacBook-Pro FireBlogs-YouTube-Finished-Source-Code % sudo npm install
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /Users/ms/Projects/FireBlogs-YouTube-Finished-Source-Code/node_modules/acorn
npm ERR! dest /Users/ms/Projects/FireBlogs-YouTube-Finished-Source-Code/node_modules/.acorn-N9aErJTn
npm ERR! errno -66
npm ERR! ENOTEMPTY: directory not empty, rename '/Users/ms/Projects/FireBlogs-YouTube-Finished-Source-Code/node_modules/acorn' -> '/Users/ms/Projects/FireBlogs-YouTube-Finished-Source-Code/node_modules/.acorn-N9aErJTn'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ms/.npm/_logs/2022-01-06T16_53_42_848Z-debug-0.log
ms@Ms-MacBook-Pro FireBlogs-YouTube-Finished-Source-Code % npm run serve

> fireblogs@0.1.0 serve
> vue-cli-service serve

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '@vue/cli-shared-utils'
Require stack:
- /Users/ms/Projects/FireBlogs-YouTube-Finished-Source-Code/node_modules/@vue/cli-service/bin/vue-cli-service.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/ms/Projects/FireBlogs-YouTube-Finished-Source-Code/node_modules/@vue/cli-service/bin/vue-cli-service.js:3:27)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/ms/Projects/FireBlogs-YouTube-Finished-Source-Code/node_modules/@vue/cli-service/bin/vue-cli-service.js'
  ]
}
ms@Ms-MacBook-Pro FireBlogs-YouTube-Finished-Source-Code % npm install     
npm ERR! code ENOTEMPTY
npm ERR! syscall rename
npm ERR! path /Users/ms/Projects/FireBlogs-YouTube-Finished-Source-Code/node_modules/acorn-walk
npm ERR! dest /Users/ms/Projects/FireBlogs-YouTube-Finished-Source-Code/node_modules/.acorn-walk-cqDuPq6B
npm ERR! errno -66
npm ERR! ENOTEMPTY: directory not empty, rename '/Users/ms/Projects/FireBlogs-YouTube-Finished-Source-Code/node_modules/acorn-walk' -> '/Users/ms/Projects/FireBlogs-YouTube-Finished-Source-Code/node_modules/.acorn-walk-cqDuPq6B'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ms/.npm/_logs/2022-01-06T17_10_52_790Z-debug-0.log
ms@Ms-MacBook-Pro FireBlogs-YouTube-Finished-Source-Code % npm run serve   

> fireblogs@0.1.0 serve
> vue-cli-service serve

node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '@vue/cli-shared-utils'
Require stack:
- /Users/ms/Projects/FireBlogs-YouTube-Finished-Source-Code/node_modules/@vue/cli-service/bin/vue-cli-service.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/ms/Projects/FireBlogs-YouTube-Finished-Source-Code/node_modules/@vue/cli-service/bin/vue-cli-service.js:3:27)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/ms/Projects/FireBlogs-YouTube-Finished-Source-Code/node_modules/@vue/cli-service/bin/vue-cli-service.js'
  ]
}
ms@Ms-MacBook-Pro FireBlogs-YouTube-Finished-Source-Code % 
![Screenshot 2022-01-06 at 18 19 19](https://user-images.githubusercontent.com/7805561/148423596-1ac36ea5-fcbf-427a-8d68-1dadf4bff051.jpg)
![Screenshot 2022-01-06 at 18 19 11](https://user-images.githubusercontent.com/7805561/148423610-acacbbd4-7338-4fb3-abe3-433024855e18.jpg)

**Comment by m-schou** [comment]
Solution: 6 hours later, downgrade to NODE 14 and it runs.
https://nodejs.org/en/blog/release/v14.17.3/

**Comment by abhi9-s** [comment]
> Solution: 6 hours later, downgrade to NODE 14 and it runs. https://nodejs.org/en/blog/release/v14.17.3/

@m-schou, you are a lifesaver for beginners. Thanks, man!

**Comment by HiddenWorldsLLC** [comment]
If you are using this in a production environment and the wrong people come across your page, they could have a lot of fun with your webpage. lol
